 CREATE DATABASE `test1`CHARACTER SET utf8 COLLATE utf8_general_ci;
 CREATE DATABASE `test2`CHARACTER SET utf8 COLLATE utf8_general_ci;
 CREATE DATABASE `test3`CHARACTER SET utf8 COLLATE utf8_general_ci;
 CREATE DATABASE `test4`CHARACTER SET utf8 COLLATE utf8_general_ci;
 CREATE DATABASE `test5`CHARACTER SET utf8 COLLATE utf8_general_ci;
 CREATE DATABASE `test6`CHARACTER SET utf8 COLLATE utf8_general_ci;
 CREATE DATABASE `test7`CHARACTER SET utf8 COLLATE utf8_general_ci;
 CREATE DATABASE `test8`CHARACTER SET utf8 COLLATE utf8_general_ci;
 CREATE DATABASE `test9`CHARACTER SET utf8 COLLATE utf8_general_ci;
 CREATE DATABASE `test10`CHARACTER SET utf8 COLLATE utf8_general_ci;
 CREATE DATABASE `test11`CHARACTER SET utf8 COLLATE utf8_general_ci;


 CREATE TABLE `test1`.`supplier`( `id` BIGINT NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `age` INT, PRIMARY KEY (`id`) ) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_general_ci;
 CREATE TABLE `test2`.`supplier`( `id` BIGINT NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `age` INT, PRIMARY KEY (`id`) ) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_general_ci;
 CREATE TABLE `test3`.`supplier`( `id` BIGINT NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `age` INT, PRIMARY KEY (`id`) ) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_general_ci;
 CREATE TABLE `test4`.`supplier`( `id` BIGINT NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `age` INT, PRIMARY KEY (`id`) ) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_general_ci;
 CREATE TABLE `test5`.`supplier`( `id` BIGINT NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `age` INT, PRIMARY KEY (`id`) ) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_general_ci;
 CREATE TABLE `test6`.`supplier`( `id` BIGINT NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `age` INT, PRIMARY KEY (`id`) ) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_general_ci;
 CREATE TABLE `test7`.`supplier`( `id` BIGINT NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `age` INT, PRIMARY KEY (`id`) ) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_general_ci;
 CREATE TABLE `test8`.`supplier`( `id` BIGINT NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `age` INT, PRIMARY KEY (`id`) ) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_general_ci;
 CREATE TABLE `test9`.`supplier`( `id` BIGINT NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `age` INT, PRIMARY KEY (`id`) ) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_general_ci;
 CREATE TABLE `test10`.`supplier`( `id` BIGINT NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `age` INT, PRIMARY KEY (`id`) ) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_general_ci;
 CREATE TABLE `test11`.`supplier`( `id` BIGINT NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `age` INT, PRIMARY KEY (`id`) ) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_general_ci;